# Generated by Django 2.2.6 on 2021-03-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycode',
            old_name='mobel',
            new_name='mobile',
        ),
    ]
