# Generated by Django 2.2.6 on 2021-03-14 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210314_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='parent_catagory',
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类目级别'),
        ),
    ]
